server:
  port: 8000
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: prod
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                skipPaths:
                  - /v3/api-docs
                  - /v3/api-docs/swagger-config
                  - /swagger-ui
                  - /swagger-ui.html
                  - /webjars
                  - /error
                  - /api/v1/auth/sign-up
                  - /api/v1/auth/sign-in
                  - /api/v1/auth/email/check-duplicate
                  - /api/v1/auth/login-id/check-duplicate
                  - /api/v1/email/send-code
                  - /api/v1/email/verify-code
                  - /api/v1/email/send-password
                  - /api/v1/oauth/sign-in
                  - /api/v1/oauth/sign-up
                  - /api/v1/agreement/**
                  - /api/v1/member/agreement/**

        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/community-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                skipPaths:
                  - /api/v1/community-service/**
                  - /api/v1/category/**
                  - /v3/api-docs
                  - /v3/api-docs/swagger-config
                  - /swagger-ui
                  - /swagger-ui.html
                  - /webjars
                  - /error
                  - /api/v1/category-list

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                skipPaths:
                  - /v3/api-docs
                  - /v3/api-docs/swagger-config
                  - /swagger-ui
                  - /swagger-ui.html
                  - /webjars
                  - /error
                  - /api/v1/profile/nickname/check-duplicate
                  - /api/v1/grade/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args:
                skipPaths:
                  - /v3/api-docs
                  - /v3/api-docs/swagger-config
                  - /swagger-ui
                  - /swagger-ui.html
                  - /webjars
                  - /error

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /

    urls:
      - name: Member Service API
        url: /member-service/v3/api-docs
      - name: Community Service API
        url: /community-service/v3/api-docs
      - name: Profile Service API
        url: /profile-service/v3/api-docs
      - name: Review Service API
        url: /review-service/v3/api-docs

logging:
  level:
    root: INFO

jwt:
  secret-key: Bt#WZxNc@M1pQ9LvUYKA8oFrTcVJX!g7qFu32LxZ$NbPCy0w